### ISSUE TITLE
Screen terminating when ctrl + c hit

### ISSUE THREAD

**Issue by sk1ll10** [skylime/mi-core-base#4]
## Problem

Screen is terminating when `ctrl + c` is hit. Seems like something is listening for this command and instantly kills the active tab.

Error persists on multiple kumquat zones for at least 2 years now. So it is very likely not related to an update.

## Steps to reproduce

* login via ssh to any kumquat zone (tested only here)
* open screen session with `screen`
* press `ctrl +c`
* screen terminates as it would get the correct command for it

## Remarks

 `ctrl + k` which would be the correct way to do this has a yes/no promt when executed so the current behavior does not seem like an an alias to this

**Comment by drscream** [comment]
The problem only exists in the old `screen` version provided by the global zone. If `screen` is installed via `pkgin` everything works fine, I do not see any possible way to fix this. I will apply some workaround which might help from avoiding `ctrl + c` on screen close.

**Comment by drscream** [comment]
Additional information from the **illumos-extra** repository. There will be a new screen version in the next releases of SmartOS: https://github.com/joyent/illumos-extra/tree/master/screen
